### ISSUE TITLE
Dashboard Localization not working

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#3436]
### Steps to Reproduce

minium reproducible repo
https://github.com/jmarsh24/localized_dashboard

video
https://share.cleanshot.com/yBMgDJ0H

Visit localhost:3000/en/avo

![Image](https://github.com/user-attachments/assets/ed42a79c-9057-4f10-b7b8-66e0585efafb)

The dashboard translation is german and not english

navigate to Visit localhost:3000/de/avo

Click on the dashboard

The locale in the url changes to en with force_locale=en

### Expected behavior & Actual behavior
I would expect the locale link if I'm on de to stay de when I click on dashboard.
I would expect the translation to respect the locale.

### System configuration
**Avo version**:
3.14

**Rails version**:
8.0

**Ruby version**:
3.3.5

**License type**:

 - [ ] Community
 - [X] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
If I understand this correctly, the engine routes are not respecting the `force_locale` scope. There is [this documentation section](https://docs.avohq.io/3.0/routing.html#mount-avo-under-a-locale-scope) explaining how to mount engine routes (e.g., Pro, dashboards, etc.) under a scope. I believe applying that should resolve the issue

**Comment by jmarsh24** [comment]
@adrianthedev @Paul-Bob We do not want to do anything special here. We only want to have a localized admin interface. All screens should be translated in german for the **de** locale and all screens should be english for **en**.

We are using force_locale because avo didn't seem to respect the localization otherwise.

**Comment by Paul-Bob** [comment]
At first glance, I thought something was misconfigured with the locale, but it seems you've configured it correctly.

The issue is that the dashboard name is set as follows: 

`self.name = I18n.t("avo.dashboards.disposals.name")`

This means that the class retains a static name according to the locale at the time it is evaluated, and it will not reload on each request.

I've just merged [this PR](https://github.com/avo-hq/avo-dashboards/pull/50), which allows you to define the dashboard name as a proc:

`self.name = -> { I18n.t("avo.dashboards.disposals.name") }`

This approach ensures it gets evaluated on each request and changes accordingly to the current locale.

This will be available on the next release

**Comment by jmarsh24** [comment]
A workaround was proposed to get the translation to work below. This does fix the issue until next release.

```
Anytime! Thanks for the repo, was really useful 
forgot to mention
if you're using avo menu
declare the i18n label on the menu, it should work until the next release
https://docs.avohq.io/3.0/menu-editor.html#dashboard
dashboard :dashy, label: I18n.t("avo.dashboards.disposals.name")
```

There is an issue with the links not maintaining the locale. I have updated the repo with the proposed fix and also attached a video demonstrating the issue if I switch to the de locale, that it switches back to en when I click on the link.

https://share.cleanshot.com/QFmktd6P

The expected behavior would be that if I'm on the de locale. Everything should translated in german and clicking on any link should still keep the german locale until I explicitly set it to english.

I would also expect to stay in on english (this is the default)

**Comment by Paul-Bob** [comment]
@jmarsh24 check this PR https://github.com/jmarsh24/localized_dashboard/pull/1

Let me know if that behaves as expected.

I'll rework the documentation a bit to reflect what we've done here.

**Comment by jmarsh24** [comment]
@Paul-Bob It seems to work! I think there is still an issue with translations in filters. Everything else in the app seems to translate now.

![Image](https://github.com/user-attachments/assets/295f19a0-1882-4e7f-b45e-77f5260b923e)

**Comment by jmarsh24** [comment]
I tried deploying to a review app but run into the following issue, but it works locally.

![Image](https://github.com/user-attachments/assets/6a6f53f3-1b0a-4613-a07f-550c94dfca38)

```
2024-11-19T21:44:47.410204+00:00 heroku[router]: at=info method=GET path="/en/admin/" host=gemeindeapp-feature-fix-d50ywy.herokuapp.com request_id=21132667-0363-4042-b178-314a8bb55509 fwd="37.120.27.216" dyno=web.1 connect=0ms service=17ms status=302 bytes=1034 protocol=https
2024-11-19T21:44:47.469684+00:00 app[web.1]: I, [2024-11-19T21:44:47.469552 #2]  INFO -- : [6927a2cb-5c93-4e04-951f-cced1993fa4a] Started GET "/en/admin/resources/events?locale=en" for 37.120.27.216 at 2024-11-19 21:44:47 +0000
2024-11-19T21:44:47.471174+00:00 app[web.1]: I, [2024-11-19T21:44:47.471091 #2]  INFO -- : [6927a2cb-5c93-4e04-951f-cced1993fa4a] Processing by Avo::EventsController#index as HTML
2024-11-19T21:44:47.471202+00:00 app[web.1]: I, [2024-11-19T21:44:47.471175 #2]  INFO -- : [6927a2cb-5c93-4e04-951f-cced1993fa4a]   Parameters: {"locale"=>"en"}
2024-11-19T21:44:47.520588+00:00 app[web.1]: I, [2024-11-19T21:44:47.520460 #2]  INFO -- : [6927a2cb-5c93-4e04-951f-cced1993fa4a]   Rendered layout vendor/bundle/ruby/3.3.0/gems/avo-3.11.2/app/views/layouts/avo/application.html.erb (Duration: 9.1ms | GC: 0.0ms)
2024-11-19T21:44:47.521026+00:00 app[web.1]: I, [2024-11-19T21:44:47.520967 #2]  INFO -- : [6927a2cb-5c93-4e04-951f-cced1993fa4a] Completed 500 Internal Server Error in 50ms (ActiveRecord: 7.1ms (13 queries, 2 cached) | GC: 0.0ms)
2024-11-19T21:44:47.523386+00:00 app[web.1]: E, [2024-11-19T21:44:47.523207 #2] ERROR -- : [6927a2cb-5c93-4e04-951f-cced1993fa4a]
2024-11-19T21:44:47.523387+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a] ActionView::Template::Error (undefined method `underscore' for an instance of Proc):
2024-11-19T21:44:47.523388+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]
2024-11-19T21:44:47.523388+00:00 app[web.1]: Causes:
2024-11-19T21:44:47.523389+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a] NoMethodError (undefined method `underscore' for an instance of Proc)
2024-11-19T21:44:47.523389+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]     3:     <%= name %>
2024-11-19T21:44:47.523390+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]     4:   </div>
2024-11-19T21:44:47.523390+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]     5:   <div class="p-4">
2024-11-19T21:44:47.523391+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]     6:     <%= yield %>
2024-11-19T21:44:47.523391+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]     7:   </div>
2024-11-19T21:44:47.523392+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]     8: </div>
2024-11-19T21:44:47.523392+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a]
2024-11-19T21:44:47.523392+00:00 app[web.1]: [6927a2cb-5c93-4e04-951f-cced1993fa4a] app/controllers/concerns/avo_localization.rb:9:in `localize'
```

**Comment by jmarsh24** [comment]
I think that there is an issue with this solution when you a proc is used in the filters. I tried assigning the name of a filter into a proc and I get the following error.

![Image](https://github.com/user-attachments/assets/b48556c7-d61e-4a34-8272-1bee1a9664ec)

**Comment by jmarsh24** [comment]
@Paul-Bob I updated the reproducible repo after merging yours with a filter with translations. All translations are set as procs and I found the following issue below where the key and value are being rendered in the filter. 

![Image](https://github.com/user-attachments/assets/2ef19cf8-5351-42de-afb3-6511dd5aa154)
![Image](https://github.com/user-attachments/assets/d810b1ad-28f1-4a35-8756-f59bdbb91cf2)

If I remove the translations I get the following
![Image](https://github.com/user-attachments/assets/655c378b-4c79-43ba-9d6f-ea06c6855d71)
![Image](https://github.com/user-attachments/assets/09d104c6-00a7-4ee7-8daa-97acd1c7eb1c)


https://github.com/jmarsh24/localized_dashboard

**Comment by Paul-Bob** [comment]
@jmarsh24 it seems your translation keys are conflicting with some default keys used by Avo.

To resolve this, run `bin/rails generate avo:locales` and verify that your keys do not overlap with the default ones.

For instance, Avo uses `avo.filters` to translate the filters button label. However, in your YAML file, you're overriding it with the following structure:

```yml
en:
  avo:
    filters: # <- Consider using something like filter_translations here, as this key is already reserved.
      featured: English Filter
```

Closing this issue since the original problem is fixed, I'll update the docs accordingly, thank you!

**Comment by Paul-Bob** [comment]
> If I add this to the application.rb it seems to fix the issue.

That's great!

If the issue persists please open a new issue and attach a way to reproduce it.

Thank you

**Comment by jmarsh24** [comment]
I have created a new issue here. I can't get the repository to break the add resource button locally, but the breadcrumbs are also not working. So far locally, it works just like this repo, but in production is changes. I tried adding caching locally but it still didn't help.

https://github.com/avo-hq/avo/issues/3445
