### ISSUE TITLE
attaching image to post 

### ISSUE THREAD

**Issue by vitaly107** [avo-hq/avo#413]
When I attach an image to a post (even on your demo site) it appears as clickable one and also inserts the hyperlink as well.

That hyperlink can be then edited as caption, otherwise it stays and shows as a link to image.

However we do not need that caption or link. Indeed, we do not want to have image clickable either.

How can this be fixed? 

Your default images in demo are not clickable and do not show any hyperlinks or captions - we want to replicate exactly the same behaviour but failed to do that locally on our own app as well as in your online demo as stated above.

Please help.

**Comment by vitaly107** [comment]
so if this is not a bug but the current state of the gem then why the demo does not reflect that? the image is not clickable on the demo and there are no links for those images that are already there? and what can could we do for now?

**Comment by adrianthedev** [comment]
The demo is populated with dummy data through seeders. They are not uploaded through Trix.

**Comment by adrianthedev** [comment]
You can test that by editing a record and adding an image

**Comment by vitaly107** [comment]
yes, I tried that and as stated above, the ugly link is inserted into demo in the same way we have it locally. this is very annoying really as we do not want to have it and do not know how to remove it. the only way is to fill in caption but then that caption becomes a link. and also the whole image is clickable and this is something unwanted.

**Comment by adrianthedev** [comment]
We'll add an option to remove the link, not sure about the caption. It's how Trix works. We'll see what we can do about that too.

**Comment by vitaly107** [comment]
many thanks, please keep use posted.

**Comment by vitaly107** [comment]
This is probably the solution we need:

https://stackoverflow.com/questions/63345323/rails-trix-editor-showing-image-and-image-size-when-caption-is-not-specified

However, how to find and amend that file inside Avo engine?

Can you do that from your end or? Many thanks

**Comment by adrianthedev** [comment]
Not sure if that can be done. You could give it a try.

**Comment by adrianthedev** [comment]
If trix is not working for you, perhaps using the custom fields feature and implementing a WYSIWYG editor that better fits your needs might be a better solution.

**Comment by vitaly107** [comment]
I tried it on a file that is from the app here

app/views/active_storage/blobs/_blob.html.erb

and it did not help, is there any other _blob.html.erb file sitting inside the engine?

can we try and change it as suggested?

**Comment by vitaly107** [comment]
I understand that I need to edit this file 
app/views/active_storage/blobs/_blob.html.erb

I also understand that the file I have in the app is not the one to be edited but the file that comes as a dependence of avo since avo comes with trix editor already

I also know that if the same file is presen tin the app and external engine then the latter takes precedence.

If those pints above are correct then can someone tell me how can I monkey patch so my
app/views/active_storage/blobs/_blob.html.erb file from the app takes the precedence over the same file that sits inside avo engine?

any help and insight would be greatly appreciated.

**Comment by adrianthedev** [comment]
We haven't been working with Trix that deep.
I recommend you clone Avo locally and try to monkey patch it and test out your ideas.

We'll schedule adding files without a link as a to-do for next week.

**Comment by vitaly107** [comment]
Hi

Can you help with this and add some instructions how to add TinyMCE editor filed instead of Trix to your docs.


I have seen progress bar example and tried follow that with little success.

Also how can I customise edit view ?

Please see the problem I face with trix field in the screen shot attached.

As soon as I switch to make it code it overflows the screen to the right – tailwind css or whatever is the bit responsible for that should be fixed.

Can you kindly fix this CSS issue from your end?

Many thanks

Vitaly

From: Adrian Marin ***@***.***>
Reply to: avo-hq/avo ***@***.***>
Date: Thursday, 27 May 2021 at 15:58
To: avo-hq/avo ***@***.***>
Cc: Vitaly Amos ***@***.***>, Author ***@***.***>
Subject: Re: [avo-hq/avo] attaching image to post (#413)


If trix is not working for you, perhaps using the custom fields feature and implementing a WYSIWYG editor that better fits your needs might be a better solution.

**Comment by adrianthedev** [comment]
Hey Vitaly, we can't see the image if you attached one. Maybe try attaching it on GitHub on the [issue page](https://github.com/avo-hq/avo/issues/413) directly?

**Comment by vitaly107** [comment]
Hi

Sorry forgot to attach the file.

Here you are.

Please let me know what you think.

Best regards

Vitaly

From: Adrian Marin ***@***.***>
Reply to: avo-hq/avo ***@***.***>
Date: Monday, 31 May 2021 at 14:17
To: avo-hq/avo ***@***.***>
Cc: Vitaly Amos ***@***.***>, Author ***@***.***>
Subject: Re: [avo-hq/avo] attaching image to post (#413)


Hey Vitaly, we can't see the image if you attached one. Maybe try attaching it on GitHub on the issue page<https://github.com/avo-hq/avo/issues/413> directly?

**Comment by adrianthedev** [comment]
We still can't see it. I think you need to visit this page https://github.com/avo-hq/avo/issues/413 and upload it there.

**Comment by vitaly107** [comment]
From: Adrian Marin ***@***.***>
Reply to: avo-hq/avo ***@***.***>
Date: Monday, 31 May 2021 at 14:19
To: avo-hq/avo ***@***.***>
Cc: Vitaly Amos ***@***.***>, Author ***@***.***>
Subject: Re: [avo-hq/avo] attaching image to post (#413)


We still can't see it. I think you need to visit this page #413<https://github.com/avo-hq/avo/issues/413> and upload it there.

**Comment by vitaly107** [comment]
I sent it as email attachment.

I cannot see how to attach/upload it to GH issue page?

Regards

Vitaly

From: Adrian Marin ***@***.***>
Reply to: avo-hq/avo ***@***.***>
Date: Monday, 31 May 2021 at 14:19
To: avo-hq/avo ***@***.***>
Cc: Vitaly Amos ***@***.***>, Author ***@***.***>
Subject: Re: [avo-hq/avo] attaching image to post (#413)


We still can't see it. I think you need to visit this page #413<https://github.com/avo-hq/avo/issues/413> and upload it there.

**Comment by vitaly107** [comment]
[Graphical user interface, text, application, email  Description automatically generated]

From: Adrian Marin ***@***.***>
Reply to: avo-hq/avo ***@***.***>
Date: Monday, 31 May 2021 at 14:19
To: avo-hq/avo ***@***.***>
Cc: Vitaly Amos ***@***.***>, Author ***@***.***>
Subject: Re: [avo-hq/avo] attaching image to post (#413)


We still can't see it. I think you need to visit this page #413<https://github.com/avo-hq/avo/issues/413> and upload it there.

**Comment by vitaly107** [comment]
Hi

I am trying tiny mce now as a custom field.

Now I need to figure out how to process image upload into page content attribute.

In JS I currently have

images_upload_url: '/uk/text_images',

I think I need to post to create action in avo page resource controller

So I can see that class so I create a create action there and can you give me some guidance here how to customise that controller in the correct way?

Many thanks

Vitaly

From: Adrian Marin ***@***.***>
Reply to: avo-hq/avo ***@***.***>
Date: Monday, 31 May 2021 at 14:19
To: avo-hq/avo ***@***.***>
Cc: Vitaly Amos ***@***.***>, Author ***@***.***>
Subject: Re: [avo-hq/avo] attaching image to post (#413)


We still can't see it. I think you need to visit this page #413<https://github.com/avo-hq/avo/issues/413> and upload it there.

**Comment by adrianthedev** [comment]
When you create a new field with TinyMCE, it's the same as you would implement it in a page for your app.

**Comment by adrianthedev** [comment]
Sorry about that. I closed it by mistake.

**Comment by adrianthedev** [comment]
When you create a new field with TinyMCE, it's the same as you would implement it in a page for your app.

You can add any action methods to a controller and upload and store the file there.

**Comment by vitaly107** [comment]
So do I add a create or upload action to the relevant resource controller?

From: Adrian Marin ***@***.***>
Reply to: avo-hq/avo ***@***.***>
Date: Monday, 31 May 2021 at 15:40
To: avo-hq/avo ***@***.***>
Cc: Vitaly Amos ***@***.***>, Author ***@***.***>
Subject: Re: [avo-hq/avo] attaching image to post (#413)


When you create a new field with TinyMCE, it's the same as you would implement it in a page for your app.

You can add any action methods to a controller and upload and store the file there.

**Comment by adrianthedev** [comment]
Probably not create because that would interfere with the resource `create` method. Something else. `upload` could be one.

**Comment by vitaly107** [comment]
and how do I find the page (model) instance in that action?

**Comment by adrianthedev** [comment]
Now you're in regular rails mode. You can change the path to something like `/uk/text_images/posts/25`. Or something similar. That's totally up to you (all regular rails code, not dependent on Avo).

**Comment by vitaly107** [comment]
sorry I am trying to add something like this

` def image_upload
    if params[:file].class == ActionDispatch::Http::UploadedFile
      @page.update(image: params[:file])
      respond_to do |format|
        if @image.save
          format.json { render json: { "location": @image.image.url }.to_json, status: :ok }
        else
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      end
    end
  end`

do you mean this should go into apps controller or into this class

`class Avo::PagesController < Avo::ResourcesController` ?

if this goes into avo class then what is instance finder method that I should use? I mean something like @page = Page.find9params[:id])

**Comment by adrianthedev** [comment]
You can put it wherever make more sense for your app. Whichever controller you think it's best. Then add the route to that action. It's totally up to you.

Yes, that's how you find that model.

**Comment by vitaly107** [comment]
what would be the route if I use avo::pages_controller?

`post 'image_upload', to: 'pages#image_upload' ` how do I wrap this in routes.rb file?

**Comment by adrianthedev** [comment]
Again, this is regular Rails code. Whatever makes sense for you.
For example: `post '/uk/pages/25/text_images', to: 'pages#image_upload'`. *but again, that's up to you and your integration.

**Comment by vitaly107** [comment]
this bit 'pages#image_upload' is inside avo - I mean I am going to use `class Avo::PagesController < Avo::ResourcesController`

what would be the correct route in this case to be put into routes file. thankyou for your clarification.

**Comment by vitaly107** [comment]
OK, it looks my route above finally worked. Howeverv I am still struggling to find the page to update:

` Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x00007fd2708c3c10 @tempfile=#<Tempfile:/var/folders/h7/qc4l3t9d08z7p3t9641l8jkm0000gn/T/RackMultipart20210531-36246-20m0zr.png>, @original_filename="about-boilerjuice.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"about-boilerjuice.png\"\r\nContent-Type: image/png\r\n">}
Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 1850)


Not notifying due to notify_release_stages :["staging", "production"]

ActiveRecord::RecordNotFound - Couldn't find Page without an ID:
  app/controllers/avo/pages_controller.rb:5:in `image_upload'
`

and this is my action:

`class Avo::PagesController < Avo::ResourcesController
  skip_before_action :verify_authenticity_token

  def image_upload
    @page = Page.friendly.find(params[:id])
    if params[:file].instance_of?(ActionDispatch::Http::UploadedFile)
      @page.update(image: params[:file])
      respond_to do |format|
        if @page.save
          redirect_back fallback_location: avo.edit_resources_page_path
        else
          redirect_back fallback_location: avo.edit_resources_page_path
        end
      end
    end
  end
end`

what am I missing here?

**Comment by vitaly107** [comment]
I am stuck with this
```

Started POST "/uk/bj-admin/resources/pages/about-boilerjuice/edit" for 127.0.0.1 at 2021-05-31 17:11:49 +0100
Processing by Avo::RelationsController#create as */*
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x00007fe31918ccf8 @tempfile=#<Tempfile:/var/folders/h7/qc4l3t9d08z7p3t9641l8jkm0000gn/T/RackMultipart20210531-60070-1gjws7j.png>, @original_filename="about-boilerjuice.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"about-boilerjuice.png\"\r\nContent-Type: image/png\r\n">, "resource_name"=>"pages", "id"=>"about-boilerjuice", "related_name"=>"edit"}
Can't verify CSRF token authenticity.
```

Please help.

Not sure why is says:
`
Processing by Avo::RelationsController#create as */*` whereas my route is as follows:

```
  scope module: 'avo' do
      post '/pages/:id/image_upload', to: 'pages#create'
    end
```

I tried adding  
`  skip_before_action :verify_authenticity_token, only: [:upload_image]`

to this controller
`class Avo::PagesController < Avo::ResourcesController`

but that did not help.

**Comment by adrianthedev** [comment]
Again Vitaly, don't overthink it. Don't think you should use Avo controllers. **You can use your own**.

Add the method as if you're implementing TinyMCE for your own. Uploading that file has nothing to do with Avo.

**Comment by adrianthedev** [comment]
Fixed by https://github.com/avo-hq/avo/pull/425

**Comment by adrianthedev** [comment]
Released in [1.7.3](https://rubygems.org/gems/avo/versions/1.7.3)
