### ISSUE TITLE
[BUG] Generate avo:resource with a model inside namespace

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [avo-hq/avo#480]
### Describe the bug
Generate avo:resource with a model inside namespace raises Zeitwerk::NameError.

### Steps to Reproduce
1. Create a model inside a namespace like `rails g model Questions::Repo`
2. Run rails and go to avo admin homepage
3. In resource section, avo shows this command: `bin/rails generate avo:resource Questions::Model `
4. Run that command `rails generate avo:resource Questions::Model `
5. Will create two files: ```
      create  app/avo/resources/model_resource.rb
      create  app/controllers/avo/models_controller.rb ```
6. Refresh avo admin;
7. Raises error   `Zeitwerk::NameError (expected file path/app/avo/resources/repo_resource.rb to define constant ModelRepo, but didn't): `

### Expected behavior
Create this files:
```
create  app/avo/resources/questions/repo_resource.rb
create  app/controllers/avo/questions/repo_controller.rb
```
### Actual behavior
Create wrong file paths.
The file path to my model (Questions::Repo) resource is app/avo/resources/repo.rb, but the class name is Questions::RepoResource.

### System configuration
**Avo version**: 1.11.6

**Rails version**: 6.1.4

**Ruby version**: 2.7.2

**Comment by adrianthedev** [comment]
Hmmm... yeah, it seems we didn't consider namespaces for generators.

Would it be possible to make a PR for this feature?

**Comment by mschiller** [comment]
I tried to set model_class => self.model_class = Spree::Store
and got this error => 

NoMethodError - undefined method `resources_stores_path' for #<ActionDispatch::Routing::RoutesProxy:0x0000000112989d48 @scope=#<Avo::HomeController

Seems, that the namespace will not be taken into account.

Any idea how to proceed?

**Comment by adrianthedev** [comment]
Hmm... interesting. 
Not sure how to create a namespace route helper. Should that be `resources_spree_stores_path`? Do you have any idea?

If yes, I can publish a pre-release version for you to test out.

**Comment by mschiller** [comment]
Hmm, I think, this convention is the right way to handle this. So, yes, let's try this out. Many thanks!

**Comment by PedroAugustoRamalhoDuarte** [comment]
@mschiller A partial fix to this issue is create a resource outside namespace, like spree_store_resource.rb:
```ruby
class SpreeStoreResource < Avo::BaseResource
  self.model_class = Spree::Store
end
```
and controller spree_stores_controller.rb:
```ruby
class Avo::SpreeStoresController < Avo::ResourcesController
end
```

**Comment by adrianthedev** [comment]
I think this is the acceptable fix. Because the controller is being generated we can't infer the controller from the new `model_class` with the added namespace.

Added a [section in the documentation](https://docs.avohq.io/1.0/resources.html#custom-model-class) about that.

Thank you @PedroAugustoRamalhoDuarte for the fix!

**Comment by mschiller** [comment]
The section in https://docs.avohq.io/1.0/resources.html#custom-model-class can't work because of a Zeitwerk::NameError: the filename must reflect the class name.

```
# app/avo/resource/store_resource.rb
class SpreeStoreResource < Avo::BaseResource
  self.model_class = Spree::Store
end

```

Btw, tried to setup the files in mentioned way above, it doesn't work:

undefined method `resources_stores_path' for #<ActionDispatch::Routing::RoutesProxy:0x000000011e8ad968 @scope=# ...

I tried the current github version.

**Comment by adrianthedev** [comment]
Ok, that error sounds legit.

Let's try something else. Do not rename the resource file **or class**. So leave the `class StoreResource` in the file `app/avo/resource/store_resource.rb` with that model class. And rename the controller `class SpreeStoresController` in the `app/controllers/avo/spree_stores_controller.rb`.

I updated the docs as well.

**Comment by mschiller** [comment]
@adrianthedev, this can't work with zeitgeist. Because...

app/controllers/**avo**/spree_stores_controller.rb needs class **Avo::**SpreeStoresController

**Comment by adrianthedev** [comment]
hmm... what about `class Avo::SpreeStoresController` in the file `app/controllers/avo/spree_stores_controller.rb ` Doesn't that work?

**Comment by HusseinMorsy** [comment]
Nearly one year later the  described bug @PedroAugustoRamalhoDuarte  is still present in the current version (2.24.0).
Because our rails applications are using namespaces models, we can't use Avo. 
(Even if we set  self.model_class , the solution don't work if the models are related with has_many)

**Comment by adrianthedev** [comment]
Can you post an example of a configuration that doesn't work for you?

**Comment by HusseinMorsy** [comment]
thanks @adrianthedev  for the fast response 👍 

1. `rails new demo`
2. `rails app:template LOCATION='https://avohq.io/app-template'`
3. `bin/rails g model store/book title:string`
4. `bin/rails server`

==> `raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)`

**Comment by adrianthedev** [comment]
Yes, So this is a bug with our generators, and we'll have that fixed for our next release.

Avo 2 has this limitation that you can't use namespaced resources, but they can be augmented with collapsing the namespace in the name.

Example:

For the `Store::Book` model, instead of having the `Store::BookResource` you'll have `StoreBookResource` and instead of `Avo::Store::BooksController` you'll have `Avo::StoreBooksController`. 
That will work with the current Avo version, solve your use-case, and have you use Avo from today 🙌

You'll also need to add `self.model_class = "Store::Book"` to that resource.

See this recording for this migration process.
https://share.cleanshot.com/NzRgYwVk

**Comment by adrianthedev** [comment]
I'm curious @PedroAugustoRamalhoDuarte, did you manage to get over this issue in your use-case?

**Comment by adrianthedev** [comment]
Please track this issue @HusseinMorsy https://github.com/avo-hq/avo/issues/1534

**Comment by PedroAugustoRamalhoDuarte** [comment]
> I'm curious @PedroAugustoRamalhoDuarte, did you manage to get over this issue in your use-case?

I use this way: https://github.com/avo-hq/avo/issues/480#issuecomment-1025668128

And has_many fields work as well.

```ruby
# Resource
class ScheduledExamsModelResource < Avo::BaseResource
  self.model_class = ScheduledExams::Model
  
  field :responses, as: :has_many
end

# Model
class ScheduledExams::Model < ApplicationRecord
  has_many :responses, class_name: 'ScheduledExams::Response', foreign_key: 'scheduled_exams_model_id',
                       dependent: :destroy, inverse_of: :scheduled_exam
end
```

**Comment by HusseinMorsy** [comment]
@adrianthedev thank you very much for the workaround and the provided screencast. You saved my day 🎉. Thank you very much. 🌟
